theme: jekyll-theme-tactile
title: <font color="#454545">The 3rd Workshop on Blockchain-enabled Networked Sensor Systems (BlockSys 2020) <font><br/><font color="#454545">November 16, 2020, Yokohama, Japan (Virtual)<font>
