theme: jekyll-theme-tactile
title: <h1> <font color="#454545">The 1st ACM International Workshop on Blockchain-enabled Networked Sensor Systems (BlockSys 2018) <font></h1><br/><h2> <font color="black">Nov. 4th 2018, Shenzhen China <font></h2>
