theme: jekyll-theme-tactile
title: <h1> <font color="black">The 1st ACM International Workshop on Blockchain-enabled Networked Sensor Systems (BCNS 2018) <font></h1><br/><h2> <font color="black">Nov. 4th, Shenzhen China <font></h2>
