theme: jekyll-theme-tactile
title: <h1> <font color="#454545">The 2nd Workshop on Blockchain-enabled Networked Sensor Systems (BlockSys 2019) <font></h1><br/><h2> <font color="black">November 4th 2018, Shenzhen China<font></h2>
