theme: jekyll-theme-tactical
title: <font color="#454545">The 2nd Workshop on Blockchain-enabled Networked Sensor Systems (BlockSys 2019) <font><br/><font color="#454545">November 10th 2019, Columbia University, New York<font>
